# Site settings
title: DiCaprio Blog
SEOTitle: 安腾青司的博客 | DiCaprio Blog
header-img: img/home-bg1.jpg
email: DiCaprio17h@gmail.com
description: "今日一别，从此天涯路远"
keyword: "DiCaprio, DiCaprio Blog, 安腾青司的博客"
url: "http://dicaprio17.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/dicaprio17/dicaprio17.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "When you break through the clouds, you will know where dreams are."
sidebar-avatar: /img/DiCaprio.jpeg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     dicaprio17
zhihu_username:     dicaprio17
github_username:    dicaprio17
facebook_username:  dicaprio17
jianshu_username:   dicaprio17
#twitter_username:   dicaprio17




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: dicaprio17

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 91a6b57cbb4a20191490                            #生成的clientID
  clientSecret: 0de92236b7f488a0200543fb854e8083fca91fed    #生成的clientSecret
  repo: dicaprio17.github.io    #仓库名称
  owner: dicaprio17    #github用户名
  admin: dicaprio17
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 483e0dbf1e12b66eea9d21ecc5fbdb07

# Google Analytics
#ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
#ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "CSDN",
        href: "https://blog.csdn.net/qq_36910634"
    }
]
